### ISSUE TITLE
CAS example with attributes populated

### ISSUE THREAD

**Issue by bzhang4sacstate** [lyrasis/aspace-oauth#10]
I was able to configure CAS to authenticate, but do not know how to populate user information (full name, first name, last name, title, etc.) to AS's user details.  I would really appreciate a config example that includes those fields.  It will also be helpful if there is a way to dump all the attributes return by CAS in the log.

thanks
Bin Zhang
bzhang@csus.edu

**Comment by mark-cooper** [comment]
@bzhang4sacstate I have some staff travel coming up and this isn't otherwise a high priority issue for us internally so I can't promise anything but I'll try to look into this in the near future.

**Comment by bzhang4sacstate** [comment]
thanks Mark.  Is there a quick way to dump all the responses from the idp, so I can see if the attributes are being sent?  Our idp vendor claims all attributes were sent back to AS/aspace-oauth.

**Comment by mark-cooper** [comment]
@bzhang4sacstate easiest way would be to inspect the auth_hash somewhere in here:

https://github.com/lyrasis/aspace-oauth/blob/master/frontend/controllers/oauth_controller.rb#L9-L35

**Comment by mark-cooper** [comment]
Hi @bzhang4sacstate 

It's been a while, but if it's still relevant there's more info here:

https://github.com/lyrasis/aspace-oauth/issues/17
