### ISSUE TITLE
Support for Azure AD?

### ISSUE THREAD

**Issue by kehh** [lyrasis/aspace-oauth#16]
Hi - this is more of a question than an issue, but do you know if this plugin supports Azure AD? That appears to support both SAML and Oauth 2.0 (https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols).

**Comment by mark-cooper** [comment]
@kehh I don't believe we've integrated with Azure AD but as it supports SAML 2.0 I'd expect it to work if you can supply the appropriate configuration for it (which can be more or less challenging depending on the IDP requirements). We have some sample config in the README but there's more to be found at:

https://github.com/omniauth/omniauth-saml
