### ISSUE TITLE
SAML with Attributes

### ISSUE THREAD

**Issue by atlasntefft** [lyrasis/aspace-oauth#17]
I'm having difficulty importing attributes such as first_name and last_name.
I've confirmed the value are getting sent over in the SAML response and it appears that they are both requested by default based on the metadata and the omniauth configuration.

In the config.rb I have them specified as shown below.
Both Full name and Email fill in fine.  I'm just not sure what I'm missing for the other fields.

      },
      :attribute_statements => {
        email: ["urn:oid:0.9.2342.19200300.100.1.3"],
		name: ["urn:oid:2.16.840.1.113730.3.1.241"],
		first_name: ["urn:oid:2.5.4.42"],
		last_name: ["urn:oid:2.5.4.4"],
      },

The relevant part of the SAML response looks like this:

 <saml2:Attribute Name="urn:oid:2.5.4.42" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml2:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">FTest1</saml2:AttributeValue>
            </saml2:Attribute>
            <saml2:Attribute Name="urn:oid:2.5.4.4" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml2:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">LTest1</saml2:AttributeValue>

Thanks in advance for any pointers!

**Comment by mark-cooper** [comment]
Hi @atlasntefft 

One problem at least is that we're not doing anything with those properties currently, even if available. It looks like we can safely attempt to access them per:

https://github.com/omniauth/omniauth/wiki/Auth-Hash-Schema#schema-10-and-later

I can make a branch that you can try out to see if it gives the expected results.

**Comment by mark-cooper** [comment]
Hi @atlasntefft 

Here's the branch to try out: https://github.com/lyrasis/aspace-oauth/tree/more-info

**Comment by atlasntefft** [comment]
Thanks, Mark!  That put me on the right path.  I changed the field for telephone and added fields for title and department and all the values came over successfully.  This is a big help for us and our clients!
[asoauth.zip](https://github.com/lyrasis/aspace-oauth/files/5914677/asoauth.zip)

Attached is what I'm using now.  It would be great if this would become part of the official package.  Would save us from having to manually replace the file each time we build another server or upgrade an existing one.

**Comment by mark-cooper** [comment]
Done! -- https://github.com/lyrasis/aspace-oauth/pull/19
