### ISSUE TITLE
Username Limitations

### ISSUE THREAD

**Issue by atlasntefft** [lyrasis/aspace-oauth#18]
We've had a couple of instances where the OAuth plugin didn't like the assertations from the customer.  One was a special character in the username (eg: first.last) and the other was that the username was in all caps (eg: FLAST)

ArchivesSpace appears to support usernames in all caps and with a period when creating accounts manually however when logging in via OAuth the plugin simply won't accept them, giving a generic "Authentication Error" upon login.

Having our clients adjust their IdPs to provide assertations in all lower-case and without any special characters provides a successful login however both clients have expressed displeasure with this requirement.

Is it possible to modify the plugin to accept these types of responses?  Perhaps this was an intentional choice due to requirements in previous versions of ArchivesSpace?

Thanks!

**Comment by atlasntefft** [comment]
I've got some clarifying information.  It turns out that the problem centers around upper-case characters in the attributes only.

Special characters do not appear to cause a problem.  With that customer, they had uppercase letters along with the special characters, and when I asked them to try an account without special characters the test account had no uppercase letters either.  Apologies for the confusion!

Our Dev team has reviewed the code and pointed out this line:
https://github.com/lyrasis/aspace-oauth/blob/master/backend/model/asoauth.rb#L29

They report that the username comes into the authenticate function lowercased like it should but info['username'] is the raw value returned from the IdP.  Any cleanup that aspace does to the username at all (like the lowercasing) will cause that check to fail.

Any advice you could give to get around this would be most welcome.  It's only been two clients so far with uppercase characters but we expect that number to grow since this plugin is highly desired especially with institutions who like to use MFA with their apps and implement it via their IdP.

Thanks again!

**Comment by mark-cooper** [comment]
Hi @atlasntefft 

I think you may be running into an ArchivesSpace issue -- I don't think it's the plugin. In an empty ArchivesSpace if you create a user with username `test`, then a user with username `TEST` the validations do not allow you to do it. Are you sure there aren't existing usernames colliding with the incoming ones? If there are delete the existing users so that the incoming ones can be created with the correct form. For instance if you have a user `test` and a user attempting to authenticate with a username of `TEST` (via oauth) it will error, so you could delete the existing user to allow the new one (with correct case) to be created.

**Comment by atlasntefft** [comment]
Hi Mark,

We're quite certain collisions are not the case.   We've done testing on a fresh database where no user accounts beyond admin exist.  Whenever an assertation comes through including an uppercase character we'd get the generic "Authentication Error" upon login and no account would be created.  

We've even gone as far as creating another test IdP and manually modified the assertations to recreate the issue.  As soon as we construct an assertion that is all lowercase characters the plugin will work great and a new account will be created.
