### ISSUE TITLE
Addressable locked at 2.8.0

### ISSUE THREAD

**Issue by atlasntefft** [lyrasis/aspace-oauth#24]
Greetings,

When installing the latest oauth plugin (Dated 9/1/21) I get an error regarding the gems on ArchivesSpace 3.1.0.
This does not happen when used on previous versions of ArchivesSpace (Tested 2.8.1 and 3.0.2).
I am able to get the plugin dated 4/22/21 working on ASpace 3.1.0 which predates the "[Locks addressable to 2.7](https://github.com/lyrasis/aspace-oauth/commit/311f072c7ebb99293a33d8301ad87e4b1159d875)" commit I see from Blake on July 3rd.

The exact message is below:

`You have requested: addressable = 2.7.0 The bundle currently has addressable locked at 2.8.0. Try running `bundle update addressable` If you are updating multiple gems in your Gemfile at once, try passing them all to `bundle update` from /archivesspace/gems/gems/bundler-2.1.4/lib/bundler/resolver.rb:290:in `block in verify_gemfile_dependencies_are_found!' from org/jruby/RubyArray.java:1809:in `each' from /archivesspace/gems/gems/bundler-2.1.4/lib/bundler/resolver.rb:258:in `verify_gemfile_dependencies_are_found!' from /archivesspace/gems/gems/bundler-2.1.4/lib/bundler/resolver.rb:49:in `start' from /archivesspace/gems/gems/bundler-2.1.4/lib/bundler/resolver.rb:22:in `resolve' from /archivesspace/gems/gems/bundler-2.1.4/lib/bundler/definition.rb:258:in `resolve' from /archivesspace/gems/gems/bundler-2.1.4/lib/bundler/definition.rb:170:in `specs' from /archivesspace/gems/gems/bundler-2.1.4/lib/bundler/definition.rb:237:in `specs_for' from /archivesspace/gems/gems/bundler-2.1.4/lib/bundler/definition.rb:226:in `requested_specs' from /archivesspace/gems/gems/bundler-2.1.4/lib/bundler/runtime.rb:101:in `block in requested_specs' from /archivesspace/gems/gems/bundler-2.1.4/lib/bundler/runtime.rb:20:in `setup' from /archivesspace/gems/gems/bundler-2.1.4/lib/bundler.rb:149:in `setup' from /archivesspace/gems/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `block in <main>' from /archivesspace/gems/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136:in `with_level' from /archivesspace/gems/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88:in `silence' from /archivesspace/gems/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `<main>' from org/jruby/RubyKernel.java:974:in `require' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:130:in `require' from /archivesspace/data/tmp/jetty-0.0.0.0-8080-frontend.war-_-any-/webapp/WEB-INF/config/boot.rb:10:in `<main>' from org/jruby/RubyKernel.java:974:in `require' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54:in `require' from uri:classloader:/jruby/rack/rails/environment3.rb:23:in `load_environment' from uri:classloader:/jruby/rack/rails_booter.rb:83:in `load_environment' from <script>:1:in `<main>' from launcher/launcher.rb:89:in `start_server' from launcher/launcher.rb:162:in `main' from launcher/launcher.rb:258:in `<main>'
`
Thanks,
Nathan

**Comment by mark-cooper** [comment]
@atlasntefft wow, I completely messed this issue, sorry. So long after the fact I believe the answer is that we're compatible as is with ASpace 3.2.0.
