### ISSUE TITLE
Bundler could not find compatible versions for gem "strscan"

### ISSUE THREAD

**Issue by sehqlr** [lyrasis/aspace-oauth#40]
Hey y'all, I installed the plugin according to the instructions, and my 3.4.1 deployment of aspace throws this error:

```
Bundler could not find compatible versions for gem "strscan":  In snapshot (Gemfile.lock): strscan (= 3.0.6) In Gemfile: rails (~> 5.2) java was resolved to 5.2.8.1, which depends on actionmailer (= 5.2.8.1) java was resolved to 5.2.8.1, which depends on mail (~> 2.5, >= 2.5.4) java was resolved to 2.8.1, which depends on net-imap java was resolved to 0.2.2, which depends on strscan java rexml (~> 3.2, >= 3.2.5, < 3.2.9) java was resolved to 3.2.8, which depends on strscan (>= 3.0.9) java Running `bundle update` will rebuild your snapshot from scratch, using only the gems in your Gemfile, which may resolve the conflict
```

This is a production deployment of aspace, which means that I don't have access to bundler, which means I cannot follow the recommended instructions from the error message. Please advise.

**Comment by sehqlr** [comment]
I found something on the main repo: https://github.com/archivesspace/archivesspace/blob/v3.4.1/frontend/Gemfile.lock#L313

What this means is that our deployed version of Aspace is incompatible with this most recent version of aspace-oauth. I'm going to look for a version of this plugin that I can use with my deployment...

**Comment by mark-cooper** [comment]
Hi @sehqlr 

You could so something like this: https://github.com/lyrasis/aspace-oauth/compare/master...pin-3.3-compat

**Comment by sehqlr** [comment]
@mark-cooper Thanks for the suggestion!

I figured out a workaround: what I ended up doing was pinning `strscan` to version 3.0.6 in the plugin's Gemfile prior to initialization with aspace. This allowed the plugin to run.

I'm reporting this result here just in case it helps someone else... and I'm closing the issue.
