### ISSUE TITLE
ASpace 4.0.0 Compatibility

### ISSUE THREAD

**Issue by atlasntefft** [lyrasis/aspace-oauth#42]
It's early yet but we've been testing the 4.0.0 release candidate and are having trouble loading the OAuth plugin.
Do you have an ETA for any compatibility updates?

Our Chief Technology Innovation Officer commented:
> The issue with the oauth plugin is that it is specifying a gem that ArchivesSpace also uses and they are specifying it using different versioning rules. AS is specifying an exact match of version 2.8.7 (i.e. = 2.8.7) while the plugin is specifying ~> 2.8 which is shorthand for >= 2.8 and < 3.0.

Thanks!

**Comment by mark-cooper** [comment]
Hi @atlasntefft you can expect that it will be updated shortly before, or shortly after the next release is made generally available. But of course there may be an extra week or two to allow for with the holiday period coming up fast.

**Comment by atlasntefft** [comment]
Excellent news!  Thank you!
